# Generated by Django 5.1.7 on 2025-04-01 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("senha", models.CharField(max_length=255)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("activate", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=500)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Bebidas", "Bebidas"),
                            ("Doces", "Doces"),
                            ("Salgados", "Salgados"),
                            ("Padaria", "Padaria"),
                            ("Mercearia", "Mercearia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estoque", models.IntegerField()),
            ],
            options={
                "db_table": "produtos",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("senha", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Divida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("activate", models.BooleanField(default=True)),
                (
                    "data_modificacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakary_village.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "dividas",
            },
        ),
        migrations.CreateModel(
            name="ClienteProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=15)),
                ("quantidade", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=15)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakary_village.cliente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakary_village.produto",
                    ),
                ),
            ],
            options={
                "db_table": "cliente_produto",
            },
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=15)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakary_village.cliente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakary_village.produto",
                    ),
                ),
            ],
            options={
                "db_table": "carrinho",
            },
        ),
    ]
